# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3e02b59577c94675243ad7f2825f8133a8e69be242d08186e255718dc5896ba44657a0e4e35991121e3de21f3be05eeb0586f6c22e70a80942ecd23eefbb8e

test:
  secret_key_base: 6d5ac71fb46759311a3ed037a38457805b308660b7abb13bdd82d30d05708b75e3e7888ea4fb6e4d793a424962667667f7a8faa9e2b557db093c7a3af33d234c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
